modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/cao-awa/annuus/issues"
license = "GPLv3"

[[mods]]
modId = "annuus"
version = "${version}"
displayName = "Annuus"
authors = "cao_awa"
description = '''
Annuus is a mod for minecraft networking, improves network performance and makes the game more available for running on large server.
'''
#logoFile = ""

[[dependencies.annuus]]
modId = "neoforge"
type = "required"
versionRange = "[21.4.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.annuus]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "annuus.mixins.json"
